apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: propdev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: propdev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditor
  namespace: propdev
